# Using Dask with TimeCopilot

In [2]:
import nest_asyncio

nest_asyncio.apply()

from timecopilot import TimeCopilotForecaster

import dask.dataframe as dd
import pandas as pd

from timecopilot.models import SeasonalNaive
from timecopilot.models.foundation.chronos import Chronos

 See https://github.com/google-research/timesfm/blob/master/README.md for updated APIs.

## Create the dataframe

In [3]:
pd_df = pd.read_csv("https://timecopilot.s3.amazonaws.com/public/data/events_pageviews.csv", parse_dates=['ds'])
df = dd.from_pandas(pd_df)
df.head()

     unique_id         ds      y
0  Oktoberfest 2020-01-31  25376
1  Oktoberfest 2020-02-29  28470
2  Oktoberfest 2020-03-31  23816
3  Oktoberfest 2020-04-30  46186
4  Oktoberfest 2020-05-31  31213

## Create a TimeCopilotForecaster

In [4]:
tcf = TimeCopilotForecaster(
    models=[
        SeasonalNaive(),
        Chronos("autogluon/chronos-2-small")
    ]
)

## Create a Forecast

In [ ]:
result = tcf.forecast(
    df=df,
    h=12
)

2026-03-23 15:22:02,445	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
2026-03-23 15:22:02,514	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.

2026-03-23 15:22:04,635 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 7f748466334296bfdf8578237049791a initialized by task ('shuffle-transfer-7f748466334296bfdf8578237049791a', 1) executed on worker tcp://127.0.0.1:51589
2026-03-23 15:22:04,693 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 7f748466334296bfdf8578237049791a deactivated due to stimulus 'task-finished-1774293724.693407'
2026-03-23 15:22:22,637 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 7f748466334296bfdf8578237049791a initialized by task ('shuffle-transfer-7f748466334296bfdf8578237049791a', 1) executed on worker tcp://127.0.0.1:51587
2026-03-23 15:22:22,660 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 7f748466334296bfdf8578237049791a deactivated due to stimulus 'task-finished-1774293742.660038'
2026-03-23 15:31:59,193 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 7f748466334296bfdf8578237049791a initialized by task ('shuffle-transfer-7f748466334296bfdf8578237049791a', 0) executed on worker tcp://127.0.0.1:51587
2026-03-23 15:31:59,214 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 7f748466334296bfdf8578237049791a deactivated due to stimulus 'task-finished-1774294319.214437'
2026-03-23 15:32:04,851 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 7f748466334296bfdf8578237049791a initialized by task ('shuffle-transfer-7f748466334296bfdf8578237049791a', 0) executed on worker tcp://127.0.0.1:51601
2026-03-23 15:32:04,874 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 7f748466334296bfdf8578237049791a deactivated due to stimulus 'task-finished-1774294324.874474'
2026-03-23 15:32:10,789 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 7f748466334296bfdf8578237049791a initialized by task ('shuffle-transfer-7f748466334296bfdf8578237049791a', 1) executed on worker tcp://127.0.0.1:51601
2026-03-23 15:32:10,811 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 7f748466334296bfdf8578237049791a deactivated due to stimulus 'task-finished-1774294330.810997'

In [10]:
result_pd = result.compute()

`torch_dtype` is deprecated! Use `dtype` instead!
`torch_dtype` is deprecated! Use `dtype` instead!
100%|██████████| 1/1 [00:00<00:00, 71.25it/s]
100%|██████████| 1/1 [00:00<00:00, 53.71it/s]
100%|██████████| 1/1 [00:00<00:00, 80.45it/s]
100%|██████████| 1/1 [00:00<00:00, 75.77it/s]
100%|██████████| 1/1 [00:00<00:00, 87.50it/s]

In [13]:
from IPython.display import HTML
display(HTML(result_pd.to_html()))