# Using Dask with TimeCopilot

In [1]:
import nest_asyncio

nest_asyncio.apply()

from timecopilot import TimeCopilotForecaster

import dask.dataframe as dd
import pandas as pd

from timecopilot.models import SeasonalNaive
from timecopilot.models.foundation.chronos import Chronos

 See https://github.com/google-research/timesfm/blob/master/README.md for updated APIs.

## Create the dataframe

In [14]:
pd_df = pd.read_csv("https://timecopilot.s3.amazonaws.com/public/data/air_passengers.csv", parse_dates=['ds'])
df = dd.from_pandas(pd_df)
df.head()

       unique_id         ds    y
0  AirPassengers 1949-01-01  112
1  AirPassengers 1949-02-01  118
2  AirPassengers 1949-03-01  132
3  AirPassengers 1949-04-01  129
4  AirPassengers 1949-05-01  121

## Create a TimeCopilotForecaster

In [4]:
tcf = TimeCopilotForecaster(
    models=[
        SeasonalNaive(),
        Chronos("autogluon/chronos-2-small")
    ]
)

## Create a Forecast

In [ ]:
result = tcf.forecast(
    df=df,
    h=12
)

2026-03-19 18:13:38,074	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
2026-03-19 18:13:38,128	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.

2026-03-19 18:13:47,274 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle a357a355f925605411bc8b7cb5aee838 initialized by task ('shuffle-transfer-a357a355f925605411bc8b7cb5aee838', 1) executed on worker tcp://127.0.0.1:50960
2026-03-19 18:13:47,327 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle a357a355f925605411bc8b7cb5aee838 deactivated due to stimulus 'task-finished-1773958427.3274329'
2026-03-19 18:15:28,501 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle a357a355f925605411bc8b7cb5aee838 initialized by task ('shuffle-transfer-a357a355f925605411bc8b7cb5aee838', 0) executed on worker tcp://127.0.0.1:50960
2026-03-19 18:15:28,525 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle a357a355f925605411bc8b7cb5aee838 deactivated due to stimulus 'task-finished-1773958528.5242739'

In [10]:
result_pd = result.compute()
result_pd

100%|██████████| 1/1 [00:00<00:00, 57.33it/s]

        unique_id                   ds  SeasonalNaive  Chronos
0   AirPassengers  1961-01-01 00:00:00          417.0    454.0
1   AirPassengers  1961-02-01 00:00:00          391.0    430.0
2   AirPassengers  1961-03-01 00:00:00          419.0    506.0
3   AirPassengers  1961-04-01 00:00:00          461.0    504.0
4   AirPassengers  1961-05-01 00:00:00          472.0    512.0
5   AirPassengers  1961-06-01 00:00:00          535.0    584.0
6   AirPassengers  1961-07-01 00:00:00          622.0    660.0
7   AirPassengers  1961-08-01 00:00:00          606.0    668.0
8   AirPassengers  1961-09-01 00:00:00          508.0    568.0
9   AirPassengers  1961-10-01 00:00:00          461.0    488.0
10  AirPassengers  1961-11-01 00:00:00          390.0    418.0
11  AirPassengers  1961-12-01 00:00:00          432.0    468.0