# Baseline Pandas Example

This is a reference point for using a TimeCopilotForecaster with pandas rather than with the alternative distributed dataframes like pyspark, ray, and dask.

In [1]:
import nest_asyncio

nest_asyncio.apply()

from timecopilot import TimeCopilotForecaster

from timecopilot.models import SeasonalNaive
from timecopilot.models.foundation.chronos import Chronos

import pandas as pd

 See https://github.com/google-research/timesfm/blob/master/README.md for updated APIs.

## Create the dataframe

In [2]:
df = pd.read_csv("https://timecopilot.s3.amazonaws.com/public/data/events_pageviews.csv", parse_dates=['ds'])
display(df.head())

     unique_id         ds      y
0  Oktoberfest 2020-01-31  25376
1  Oktoberfest 2020-02-29  28470
2  Oktoberfest 2020-03-31  23816
3  Oktoberfest 2020-04-30  46186
4  Oktoberfest 2020-05-31  31213

## Create the TimeCopilotForecaster

In [3]:
tcf = TimeCopilotForecaster(
    models=[
        SeasonalNaive(),
        Chronos()
    ]
)

## Generate a forecast

In [4]:
result = tcf.forecast(
    df=df,
    h=12
)

`torch_dtype` is deprecated! Use `dtype` instead!
100%|██████████| 1/1 [00:07<00:00,  7.92s/it]

## Display the results

In [5]:
from IPython.display import HTML

display(HTML(result.to_html()))