# Baseline Pandas Example

This is a reference point for using a TimeCopilotForecaster with pandas rather than with the alternative distributed dataframes like pyspark, ray, and dask.

In [1]:
import nest_asyncio

nest_asyncio.apply()

from timecopilot import TimeCopilotForecaster

from timecopilot.models import SeasonalNaive
from timecopilot.models.foundation.chronos import Chronos

import pandas as pd

 See https://github.com/google-research/timesfm/blob/master/README.md for updated APIs.

## Create the dataframe

In [2]:
df = pd.read_csv("https://timecopilot.s3.amazonaws.com/public/data/air_passengers.csv", parse_dates=['ds'])
display(df.head())

       unique_id         ds    y
0  AirPassengers 1949-01-01  112
1  AirPassengers 1949-02-01  118
2  AirPassengers 1949-03-01  132
3  AirPassengers 1949-04-01  129
4  AirPassengers 1949-05-01  121

## Create the TimeCopilotForecaster

In [3]:
tcf = TimeCopilotForecaster(
    models=[
        SeasonalNaive(),
        Chronos()
    ]
)

## Generate a forecast

In [4]:
result = tcf.forecast(
    df=df,
    h=12
)

100%|██████████| 1/1 [00:14<00:00, 14.16s/it]

## Display the results

In [5]:
result

        unique_id         ds  SeasonalNaive     Chronos
0   AirPassengers 1961-01-01          417.0  448.176117
1   AirPassengers 1961-02-01          391.0  418.886902
2   AirPassengers 1961-03-01          419.0  466.777344
3   AirPassengers 1961-04-01          461.0  469.963196
4   AirPassengers 1961-05-01          472.0  500.999512
5   AirPassengers 1961-06-01          535.0  570.368652
6   AirPassengers 1961-07-01          622.0  648.884277
7   AirPassengers 1961-08-01          606.0  639.429504
8   AirPassengers 1961-09-01          508.0  525.664062
9   AirPassengers 1961-10-01          461.0  460.097351
10  AirPassengers 1961-11-01          390.0  396.380524
11  AirPassengers 1961-12-01          432.0  431.013672